[package]
name = "rspc-lite"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-core = "0.3.28"
serde = { workspace = true, default-features = false }
serde_json = "1.0.105"
specta = { workspace = true, default-features = false }
